// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: protobuf/pemain.proto

package pemainpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pemain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdPemain      int64                  `protobuf:"varint,1,opt,name=id_pemain,json=idPemain,proto3" json:"id_pemain,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClubId        int64                  `protobuf:"varint,3,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`
	MarketValue   float64                `protobuf:"fixed64,4,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	StatusPemain  string                 `protobuf:"bytes,5,opt,name=status_pemain,json=statusPemain,proto3" json:"status_pemain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pemain) Reset() {
	*x = Pemain{}
	mi := &file_protobuf_pemain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pemain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pemain) ProtoMessage() {}

func (x *Pemain) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pemain.ProtoReflect.Descriptor instead.
func (*Pemain) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{0}
}

func (x *Pemain) GetIdPemain() int64 {
	if x != nil {
		return x.IdPemain
	}
	return 0
}

func (x *Pemain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pemain) GetClubId() int64 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

func (x *Pemain) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *Pemain) GetStatusPemain() string {
	if x != nil {
		return x.StatusPemain
	}
	return ""
}

type CreatePemainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClubId        int64                  `protobuf:"varint,2,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`
	MarketValue   float64                `protobuf:"fixed64,3,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	StatusPemain  string                 `protobuf:"bytes,4,opt,name=status_pemain,json=statusPemain,proto3" json:"status_pemain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePemainRequest) Reset() {
	*x = CreatePemainRequest{}
	mi := &file_protobuf_pemain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePemainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePemainRequest) ProtoMessage() {}

func (x *CreatePemainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePemainRequest.ProtoReflect.Descriptor instead.
func (*CreatePemainRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePemainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePemainRequest) GetClubId() int64 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

func (x *CreatePemainRequest) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *CreatePemainRequest) GetStatusPemain() string {
	if x != nil {
		return x.StatusPemain
	}
	return ""
}

type GetPemainByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdPemain      int64                  `protobuf:"varint,1,opt,name=id_pemain,json=idPemain,proto3" json:"id_pemain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPemainByIDRequest) Reset() {
	*x = GetPemainByIDRequest{}
	mi := &file_protobuf_pemain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPemainByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPemainByIDRequest) ProtoMessage() {}

func (x *GetPemainByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPemainByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPemainByIDRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{2}
}

func (x *GetPemainByIDRequest) GetIdPemain() int64 {
	if x != nil {
		return x.IdPemain
	}
	return 0
}

type GetPemainByClubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClubId        int64                  `protobuf:"varint,1,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPemainByClubRequest) Reset() {
	*x = GetPemainByClubRequest{}
	mi := &file_protobuf_pemain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPemainByClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPemainByClubRequest) ProtoMessage() {}

func (x *GetPemainByClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPemainByClubRequest.ProtoReflect.Descriptor instead.
func (*GetPemainByClubRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{3}
}

func (x *GetPemainByClubRequest) GetClubId() int64 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

type UpdateByPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdPemain      int64                  `protobuf:"varint,1,opt,name=id_pemain,json=idPemain,proto3" json:"id_pemain,omitempty"`
	StatusPemain  string                 `protobuf:"bytes,2,opt,name=status_pemain,json=statusPemain,proto3" json:"status_pemain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateByPlayerRequest) Reset() {
	*x = UpdateByPlayerRequest{}
	mi := &file_protobuf_pemain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateByPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateByPlayerRequest) ProtoMessage() {}

func (x *UpdateByPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateByPlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdateByPlayerRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateByPlayerRequest) GetIdPemain() int64 {
	if x != nil {
		return x.IdPemain
	}
	return 0
}

func (x *UpdateByPlayerRequest) GetStatusPemain() string {
	if x != nil {
		return x.StatusPemain
	}
	return ""
}

type UpdateByClubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdPemain      int64                  `protobuf:"varint,1,opt,name=id_pemain,json=idPemain,proto3" json:"id_pemain,omitempty"`
	ClubId        int64                  `protobuf:"varint,2,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`
	MarketValue   float64                `protobuf:"fixed64,3,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	StatusPemain  string                 `protobuf:"bytes,4,opt,name=status_pemain,json=statusPemain,proto3" json:"status_pemain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateByClubRequest) Reset() {
	*x = UpdateByClubRequest{}
	mi := &file_protobuf_pemain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateByClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateByClubRequest) ProtoMessage() {}

func (x *UpdateByClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateByClubRequest.ProtoReflect.Descriptor instead.
func (*UpdateByClubRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateByClubRequest) GetIdPemain() int64 {
	if x != nil {
		return x.IdPemain
	}
	return 0
}

func (x *UpdateByClubRequest) GetClubId() int64 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

func (x *UpdateByClubRequest) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *UpdateByClubRequest) GetStatusPemain() string {
	if x != nil {
		return x.StatusPemain
	}
	return ""
}

type DeletePemainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdPemain      int64                  `protobuf:"varint,1,opt,name=id_pemain,json=idPemain,proto3" json:"id_pemain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePemainRequest) Reset() {
	*x = DeletePemainRequest{}
	mi := &file_protobuf_pemain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePemainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePemainRequest) ProtoMessage() {}

func (x *DeletePemainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePemainRequest.ProtoReflect.Descriptor instead.
func (*DeletePemainRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePemainRequest) GetIdPemain() int64 {
	if x != nil {
		return x.IdPemain
	}
	return 0
}

type PemainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pemain        *Pemain                `protobuf:"bytes,1,opt,name=pemain,proto3" json:"pemain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PemainResponse) Reset() {
	*x = PemainResponse{}
	mi := &file_protobuf_pemain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PemainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PemainResponse) ProtoMessage() {}

func (x *PemainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PemainResponse.ProtoReflect.Descriptor instead.
func (*PemainResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{7}
}

func (x *PemainResponse) GetPemain() *Pemain {
	if x != nil {
		return x.Pemain
	}
	return nil
}

type ListPemainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pemain        []*Pemain              `protobuf:"bytes,1,rep,name=pemain,proto3" json:"pemain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPemainResponse) Reset() {
	*x = ListPemainResponse{}
	mi := &file_protobuf_pemain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPemainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPemainResponse) ProtoMessage() {}

func (x *ListPemainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPemainResponse.ProtoReflect.Descriptor instead.
func (*ListPemainResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{8}
}

func (x *ListPemainResponse) GetPemain() []*Pemain {
	if x != nil {
		return x.Pemain
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protobuf_pemain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pemain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_pemain_proto_rawDescGZIP(), []int{9}
}

var File_protobuf_pemain_proto protoreflect.FileDescriptor

const file_protobuf_pemain_proto_rawDesc = "" +
	"\n" +
	"\x15protobuf/pemain.proto\x12\x06pemain\"\x9a\x01\n" +
	"\x06Pemain\x12\x1b\n" +
	"\tid_pemain\x18\x01 \x01(\x03R\bidPemain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aclub_id\x18\x03 \x01(\x03R\x06clubId\x12!\n" +
	"\fmarket_value\x18\x04 \x01(\x01R\vmarketValue\x12#\n" +
	"\rstatus_pemain\x18\x05 \x01(\tR\fstatusPemain\"\x8a\x01\n" +
	"\x13CreatePemainRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aclub_id\x18\x02 \x01(\x03R\x06clubId\x12!\n" +
	"\fmarket_value\x18\x03 \x01(\x01R\vmarketValue\x12#\n" +
	"\rstatus_pemain\x18\x04 \x01(\tR\fstatusPemain\"3\n" +
	"\x14GetPemainByIDRequest\x12\x1b\n" +
	"\tid_pemain\x18\x01 \x01(\x03R\bidPemain\"1\n" +
	"\x16GetPemainByClubRequest\x12\x17\n" +
	"\aclub_id\x18\x01 \x01(\x03R\x06clubId\"Y\n" +
	"\x15UpdateByPlayerRequest\x12\x1b\n" +
	"\tid_pemain\x18\x01 \x01(\x03R\bidPemain\x12#\n" +
	"\rstatus_pemain\x18\x02 \x01(\tR\fstatusPemain\"\x93\x01\n" +
	"\x13UpdateByClubRequest\x12\x1b\n" +
	"\tid_pemain\x18\x01 \x01(\x03R\bidPemain\x12\x17\n" +
	"\aclub_id\x18\x02 \x01(\x03R\x06clubId\x12!\n" +
	"\fmarket_value\x18\x03 \x01(\x01R\vmarketValue\x12#\n" +
	"\rstatus_pemain\x18\x04 \x01(\tR\fstatusPemain\"2\n" +
	"\x13DeletePemainRequest\x12\x1b\n" +
	"\tid_pemain\x18\x01 \x01(\x03R\bidPemain\"8\n" +
	"\x0ePemainResponse\x12&\n" +
	"\x06pemain\x18\x01 \x01(\v2\x0e.pemain.PemainR\x06pemain\"<\n" +
	"\x12ListPemainResponse\x12&\n" +
	"\x06pemain\x18\x01 \x03(\v2\x0e.pemain.PemainR\x06pemain\"\a\n" +
	"\x05Empty2\xef\x03\n" +
	"\rPemainService\x12C\n" +
	"\fCreatePemain\x12\x1b.pemain.CreatePemainRequest\x1a\x16.pemain.PemainResponse\x12E\n" +
	"\rGetPemainByID\x12\x1c.pemain.GetPemainByIDRequest\x1a\x16.pemain.PemainResponse\x129\n" +
	"\fGetAllPemain\x12\r.pemain.Empty\x1a\x1a.pemain.ListPemainResponse\x12G\n" +
	"\x0eUpdateByPlayer\x12\x1d.pemain.UpdateByPlayerRequest\x1a\x16.pemain.PemainResponse\x12C\n" +
	"\fUpdateByClub\x12\x1b.pemain.UpdateByClubRequest\x1a\x16.pemain.PemainResponse\x12:\n" +
	"\fDeletePemain\x12\x1b.pemain.DeletePemainRequest\x1a\r.pemain.Empty\x12M\n" +
	"\x0fGetPemainByClub\x12\x1e.pemain.GetPemainByClubRequest\x1a\x1a.pemain.ListPemainResponseB\x1eZ\x1cPemain/proto/pemain;pemainpbb\x06proto3"

var (
	file_protobuf_pemain_proto_rawDescOnce sync.Once
	file_protobuf_pemain_proto_rawDescData []byte
)

func file_protobuf_pemain_proto_rawDescGZIP() []byte {
	file_protobuf_pemain_proto_rawDescOnce.Do(func() {
		file_protobuf_pemain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_pemain_proto_rawDesc), len(file_protobuf_pemain_proto_rawDesc)))
	})
	return file_protobuf_pemain_proto_rawDescData
}

var file_protobuf_pemain_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protobuf_pemain_proto_goTypes = []any{
	(*Pemain)(nil),                 // 0: pemain.Pemain
	(*CreatePemainRequest)(nil),    // 1: pemain.CreatePemainRequest
	(*GetPemainByIDRequest)(nil),   // 2: pemain.GetPemainByIDRequest
	(*GetPemainByClubRequest)(nil), // 3: pemain.GetPemainByClubRequest
	(*UpdateByPlayerRequest)(nil),  // 4: pemain.UpdateByPlayerRequest
	(*UpdateByClubRequest)(nil),    // 5: pemain.UpdateByClubRequest
	(*DeletePemainRequest)(nil),    // 6: pemain.DeletePemainRequest
	(*PemainResponse)(nil),         // 7: pemain.PemainResponse
	(*ListPemainResponse)(nil),     // 8: pemain.ListPemainResponse
	(*Empty)(nil),                  // 9: pemain.Empty
}
var file_protobuf_pemain_proto_depIdxs = []int32{
	0, // 0: pemain.PemainResponse.pemain:type_name -> pemain.Pemain
	0, // 1: pemain.ListPemainResponse.pemain:type_name -> pemain.Pemain
	1, // 2: pemain.PemainService.CreatePemain:input_type -> pemain.CreatePemainRequest
	2, // 3: pemain.PemainService.GetPemainByID:input_type -> pemain.GetPemainByIDRequest
	9, // 4: pemain.PemainService.GetAllPemain:input_type -> pemain.Empty
	4, // 5: pemain.PemainService.UpdateByPlayer:input_type -> pemain.UpdateByPlayerRequest
	5, // 6: pemain.PemainService.UpdateByClub:input_type -> pemain.UpdateByClubRequest
	6, // 7: pemain.PemainService.DeletePemain:input_type -> pemain.DeletePemainRequest
	3, // 8: pemain.PemainService.GetPemainByClub:input_type -> pemain.GetPemainByClubRequest
	7, // 9: pemain.PemainService.CreatePemain:output_type -> pemain.PemainResponse
	7, // 10: pemain.PemainService.GetPemainByID:output_type -> pemain.PemainResponse
	8, // 11: pemain.PemainService.GetAllPemain:output_type -> pemain.ListPemainResponse
	7, // 12: pemain.PemainService.UpdateByPlayer:output_type -> pemain.PemainResponse
	7, // 13: pemain.PemainService.UpdateByClub:output_type -> pemain.PemainResponse
	9, // 14: pemain.PemainService.DeletePemain:output_type -> pemain.Empty
	8, // 15: pemain.PemainService.GetPemainByClub:output_type -> pemain.ListPemainResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_pemain_proto_init() }
func file_protobuf_pemain_proto_init() {
	if File_protobuf_pemain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_pemain_proto_rawDesc), len(file_protobuf_pemain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_pemain_proto_goTypes,
		DependencyIndexes: file_protobuf_pemain_proto_depIdxs,
		MessageInfos:      file_protobuf_pemain_proto_msgTypes,
	}.Build()
	File_protobuf_pemain_proto = out.File
	file_protobuf_pemain_proto_goTypes = nil
	file_protobuf_pemain_proto_depIdxs = nil
}
