// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: Protobuf/transfer.proto

package transferpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entity Transfer
type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTransfer    int64                  `protobuf:"varint,1,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	OldClubId     int64                  `protobuf:"varint,3,opt,name=old_club_id,json=oldClubId,proto3" json:"old_club_id,omitempty"`
	NewClubId     int64                  `protobuf:"varint,4,opt,name=new_club_id,json=newClubId,proto3" json:"new_club_id,omitempty"`
	TransferFee   float64                `protobuf:"fixed64,5,opt,name=transfer_fee,json=transferFee,proto3" json:"transfer_fee,omitempty"`
	TransferDate  string                 `protobuf:"bytes,6,opt,name=transfer_date,json=transferDate,proto3" json:"transfer_date,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // misal: pending, completed, canceled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_Protobuf_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetIdTransfer() int64 {
	if x != nil {
		return x.IdTransfer
	}
	return 0
}

func (x *Transfer) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Transfer) GetOldClubId() int64 {
	if x != nil {
		return x.OldClubId
	}
	return 0
}

func (x *Transfer) GetNewClubId() int64 {
	if x != nil {
		return x.NewClubId
	}
	return 0
}

func (x *Transfer) GetTransferFee() float64 {
	if x != nil {
		return x.TransferFee
	}
	return 0
}

func (x *Transfer) GetTransferDate() string {
	if x != nil {
		return x.TransferDate
	}
	return ""
}

func (x *Transfer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request untuk Create Transfer
type CreateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NewClubId     int64                  `protobuf:"varint,2,opt,name=new_club_id,json=newClubId,proto3" json:"new_club_id,omitempty"`
	TransferFee   float64                `protobuf:"fixed64,3,opt,name=transfer_fee,json=transferFee,proto3" json:"transfer_fee,omitempty"`
	TransferDate  string                 `protobuf:"bytes,4,opt,name=transfer_date,json=transferDate,proto3" json:"transfer_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_Protobuf_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransferRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CreateTransferRequest) GetNewClubId() int64 {
	if x != nil {
		return x.NewClubId
	}
	return 0
}

func (x *CreateTransferRequest) GetTransferFee() float64 {
	if x != nil {
		return x.TransferFee
	}
	return 0
}

func (x *CreateTransferRequest) GetTransferDate() string {
	if x != nil {
		return x.TransferDate
	}
	return ""
}

// Request ambil Transfer by ID
type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTransfer    int64                  `protobuf:"varint,1,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_Protobuf_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransferRequest) GetIdTransfer() int64 {
	if x != nil {
		return x.IdTransfer
	}
	return 0
}

// Request ambil semua Transfer
type ListTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersRequest) Reset() {
	*x = ListTransfersRequest{}
	mi := &file_Protobuf_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersRequest) ProtoMessage() {}

func (x *ListTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersRequest.ProtoReflect.Descriptor instead.
func (*ListTransfersRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{3}
}

// Response list Transfer
type ListTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersResponse) Reset() {
	*x = ListTransfersResponse{}
	mi := &file_Protobuf_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersResponse) ProtoMessage() {}

func (x *ListTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersResponse.ProtoReflect.Descriptor instead.
func (*ListTransfersResponse) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransfersResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

// Request update Transfer
type UpdateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTransfer    int64                  `protobuf:"varint,1,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"`
	NewClubId     int64                  `protobuf:"varint,2,opt,name=new_club_id,json=newClubId,proto3" json:"new_club_id,omitempty"`
	TransferFee   float64                `protobuf:"fixed64,3,opt,name=transfer_fee,json=transferFee,proto3" json:"transfer_fee,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransferRequest) Reset() {
	*x = UpdateTransferRequest{}
	mi := &file_Protobuf_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransferRequest) ProtoMessage() {}

func (x *UpdateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransferRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransferRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransferRequest) GetIdTransfer() int64 {
	if x != nil {
		return x.IdTransfer
	}
	return 0
}

func (x *UpdateTransferRequest) GetNewClubId() int64 {
	if x != nil {
		return x.NewClubId
	}
	return 0
}

func (x *UpdateTransferRequest) GetTransferFee() float64 {
	if x != nil {
		return x.TransferFee
	}
	return 0
}

func (x *UpdateTransferRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Request delete Transfer
type DeleteTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTransfer    int64                  `protobuf:"varint,1,opt,name=id_transfer,json=idTransfer,proto3" json:"id_transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransferRequest) Reset() {
	*x = DeleteTransferRequest{}
	mi := &file_Protobuf_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransferRequest) ProtoMessage() {}

func (x *DeleteTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransferRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransferRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTransferRequest) GetIdTransfer() int64 {
	if x != nil {
		return x.IdTransfer
	}
	return 0
}

// Response delete Transfer
type DeleteTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransferResponse) Reset() {
	*x = DeleteTransferResponse{}
	mi := &file_Protobuf_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransferResponse) ProtoMessage() {}

func (x *DeleteTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransferResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransferResponse) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Response single Transfer
type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_Protobuf_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_Protobuf_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *TransferResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

var File_Protobuf_transfer_proto protoreflect.FileDescriptor

const file_Protobuf_transfer_proto_rawDesc = "" +
	"\n" +
	"\x17Protobuf/transfer.proto\x12\btransfer\"\xe8\x01\n" +
	"\bTransfer\x12\x1f\n" +
	"\vid_transfer\x18\x01 \x01(\x03R\n" +
	"idTransfer\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1e\n" +
	"\vold_club_id\x18\x03 \x01(\x03R\toldClubId\x12\x1e\n" +
	"\vnew_club_id\x18\x04 \x01(\x03R\tnewClubId\x12!\n" +
	"\ftransfer_fee\x18\x05 \x01(\x01R\vtransferFee\x12#\n" +
	"\rtransfer_date\x18\x06 \x01(\tR\ftransferDate\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x9c\x01\n" +
	"\x15CreateTransferRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1e\n" +
	"\vnew_club_id\x18\x02 \x01(\x03R\tnewClubId\x12!\n" +
	"\ftransfer_fee\x18\x03 \x01(\x01R\vtransferFee\x12#\n" +
	"\rtransfer_date\x18\x04 \x01(\tR\ftransferDate\"5\n" +
	"\x12GetTransferRequest\x12\x1f\n" +
	"\vid_transfer\x18\x01 \x01(\x03R\n" +
	"idTransfer\"\x16\n" +
	"\x14ListTransfersRequest\"I\n" +
	"\x15ListTransfersResponse\x120\n" +
	"\ttransfers\x18\x01 \x03(\v2\x12.transfer.TransferR\ttransfers\"\x93\x01\n" +
	"\x15UpdateTransferRequest\x12\x1f\n" +
	"\vid_transfer\x18\x01 \x01(\x03R\n" +
	"idTransfer\x12\x1e\n" +
	"\vnew_club_id\x18\x02 \x01(\x03R\tnewClubId\x12!\n" +
	"\ftransfer_fee\x18\x03 \x01(\x01R\vtransferFee\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"8\n" +
	"\x15DeleteTransferRequest\x12\x1f\n" +
	"\vid_transfer\x18\x01 \x01(\x03R\n" +
	"idTransfer\"2\n" +
	"\x16DeleteTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x10TransferResponse\x12.\n" +
	"\btransfer\x18\x01 \x01(\v2\x12.transfer.TransferR\btransfer2\x9f\x03\n" +
	"\x0fTransferService\x12M\n" +
	"\x0eCreateTransfer\x12\x1f.transfer.CreateTransferRequest\x1a\x1a.transfer.TransferResponse\x12G\n" +
	"\vGetTransfer\x12\x1c.transfer.GetTransferRequest\x1a\x1a.transfer.TransferResponse\x12P\n" +
	"\rListTransfers\x12\x1e.transfer.ListTransfersRequest\x1a\x1f.transfer.ListTransfersResponse\x12M\n" +
	"\x0eUpdateTransfer\x12\x1f.transfer.UpdateTransferRequest\x1a\x1a.transfer.TransferResponse\x12S\n" +
	"\x0eDeleteTransfer\x12\x1f.transfer.DeleteTransferRequest\x1a .transfer.DeleteTransferResponseB\x1bZ\x19Transfer/proto/transferpbb\x06proto3"

var (
	file_Protobuf_transfer_proto_rawDescOnce sync.Once
	file_Protobuf_transfer_proto_rawDescData []byte
)

func file_Protobuf_transfer_proto_rawDescGZIP() []byte {
	file_Protobuf_transfer_proto_rawDescOnce.Do(func() {
		file_Protobuf_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_transfer_proto_rawDesc), len(file_Protobuf_transfer_proto_rawDesc)))
	})
	return file_Protobuf_transfer_proto_rawDescData
}

var file_Protobuf_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_Protobuf_transfer_proto_goTypes = []any{
	(*Transfer)(nil),               // 0: transfer.Transfer
	(*CreateTransferRequest)(nil),  // 1: transfer.CreateTransferRequest
	(*GetTransferRequest)(nil),     // 2: transfer.GetTransferRequest
	(*ListTransfersRequest)(nil),   // 3: transfer.ListTransfersRequest
	(*ListTransfersResponse)(nil),  // 4: transfer.ListTransfersResponse
	(*UpdateTransferRequest)(nil),  // 5: transfer.UpdateTransferRequest
	(*DeleteTransferRequest)(nil),  // 6: transfer.DeleteTransferRequest
	(*DeleteTransferResponse)(nil), // 7: transfer.DeleteTransferResponse
	(*TransferResponse)(nil),       // 8: transfer.TransferResponse
}
var file_Protobuf_transfer_proto_depIdxs = []int32{
	0, // 0: transfer.ListTransfersResponse.transfers:type_name -> transfer.Transfer
	0, // 1: transfer.TransferResponse.transfer:type_name -> transfer.Transfer
	1, // 2: transfer.TransferService.CreateTransfer:input_type -> transfer.CreateTransferRequest
	2, // 3: transfer.TransferService.GetTransfer:input_type -> transfer.GetTransferRequest
	3, // 4: transfer.TransferService.ListTransfers:input_type -> transfer.ListTransfersRequest
	5, // 5: transfer.TransferService.UpdateTransfer:input_type -> transfer.UpdateTransferRequest
	6, // 6: transfer.TransferService.DeleteTransfer:input_type -> transfer.DeleteTransferRequest
	8, // 7: transfer.TransferService.CreateTransfer:output_type -> transfer.TransferResponse
	8, // 8: transfer.TransferService.GetTransfer:output_type -> transfer.TransferResponse
	4, // 9: transfer.TransferService.ListTransfers:output_type -> transfer.ListTransfersResponse
	8, // 10: transfer.TransferService.UpdateTransfer:output_type -> transfer.TransferResponse
	7, // 11: transfer.TransferService.DeleteTransfer:output_type -> transfer.DeleteTransferResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Protobuf_transfer_proto_init() }
func file_Protobuf_transfer_proto_init() {
	if File_Protobuf_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_transfer_proto_rawDesc), len(file_Protobuf_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Protobuf_transfer_proto_goTypes,
		DependencyIndexes: file_Protobuf_transfer_proto_depIdxs,
		MessageInfos:      file_Protobuf_transfer_proto_msgTypes,
	}.Build()
	File_Protobuf_transfer_proto = out.File
	file_Protobuf_transfer_proto_goTypes = nil
	file_Protobuf_transfer_proto_depIdxs = nil
}
