// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: Protobuf/club.proto

package clubpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Club struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClub        int64                  `protobuf:"varint,1,opt,name=id_club,json=idClub,proto3" json:"id_club,omitempty"`
	NameClub      string                 `protobuf:"bytes,2,opt,name=name_club,json=nameClub,proto3" json:"name_club,omitempty"`
	CityClub      string                 `protobuf:"bytes,3,opt,name=city_club,json=cityClub,proto3" json:"city_club,omitempty"`
	Budget        int64                  `protobuf:"varint,4,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Club) Reset() {
	*x = Club{}
	mi := &file_Protobuf_club_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Club) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Club) ProtoMessage() {}

func (x *Club) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Club.ProtoReflect.Descriptor instead.
func (*Club) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{0}
}

func (x *Club) GetIdClub() int64 {
	if x != nil {
		return x.IdClub
	}
	return 0
}

func (x *Club) GetNameClub() string {
	if x != nil {
		return x.NameClub
	}
	return ""
}

func (x *Club) GetCityClub() string {
	if x != nil {
		return x.CityClub
	}
	return ""
}

func (x *Club) GetBudget() int64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

type CreateClubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameClub      string                 `protobuf:"bytes,1,opt,name=name_club,json=nameClub,proto3" json:"name_club,omitempty"`
	CityClub      string                 `protobuf:"bytes,2,opt,name=city_club,json=cityClub,proto3" json:"city_club,omitempty"`
	Budget        int64                  `protobuf:"varint,3,opt,name=budget,proto3" json:"budget,omitempty"` // budget awal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClubRequest) Reset() {
	*x = CreateClubRequest{}
	mi := &file_Protobuf_club_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClubRequest) ProtoMessage() {}

func (x *CreateClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClubRequest.ProtoReflect.Descriptor instead.
func (*CreateClubRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClubRequest) GetNameClub() string {
	if x != nil {
		return x.NameClub
	}
	return ""
}

func (x *CreateClubRequest) GetCityClub() string {
	if x != nil {
		return x.CityClub
	}
	return ""
}

func (x *CreateClubRequest) GetBudget() int64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

type GetClubByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClub        int64                  `protobuf:"varint,1,opt,name=id_club,json=idClub,proto3" json:"id_club,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClubByIDRequest) Reset() {
	*x = GetClubByIDRequest{}
	mi := &file_Protobuf_club_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClubByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClubByIDRequest) ProtoMessage() {}

func (x *GetClubByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClubByIDRequest.ProtoReflect.Descriptor instead.
func (*GetClubByIDRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{2}
}

func (x *GetClubByIDRequest) GetIdClub() int64 {
	if x != nil {
		return x.IdClub
	}
	return 0
}

type UpdateClubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClub        int64                  `protobuf:"varint,1,opt,name=id_club,json=idClub,proto3" json:"id_club,omitempty"`
	NameClub      string                 `protobuf:"bytes,2,opt,name=name_club,json=nameClub,proto3" json:"name_club,omitempty"`
	CityClub      string                 `protobuf:"bytes,3,opt,name=city_club,json=cityClub,proto3" json:"city_club,omitempty"` // budget tidak ikut di-update disini
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClubRequest) Reset() {
	*x = UpdateClubRequest{}
	mi := &file_Protobuf_club_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClubRequest) ProtoMessage() {}

func (x *UpdateClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClubRequest.ProtoReflect.Descriptor instead.
func (*UpdateClubRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateClubRequest) GetIdClub() int64 {
	if x != nil {
		return x.IdClub
	}
	return 0
}

func (x *UpdateClubRequest) GetNameClub() string {
	if x != nil {
		return x.NameClub
	}
	return ""
}

func (x *UpdateClubRequest) GetCityClub() string {
	if x != nil {
		return x.CityClub
	}
	return ""
}

type DeleteClubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClub        int64                  `protobuf:"varint,1,opt,name=id_club,json=idClub,proto3" json:"id_club,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClubRequest) Reset() {
	*x = DeleteClubRequest{}
	mi := &file_Protobuf_club_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClubRequest) ProtoMessage() {}

func (x *DeleteClubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClubRequest.ProtoReflect.Descriptor instead.
func (*DeleteClubRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteClubRequest) GetIdClub() int64 {
	if x != nil {
		return x.IdClub
	}
	return 0
}

type AddIncomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClub        int64                  `protobuf:"varint,1,opt,name=id_club,json=idClub,proto3" json:"id_club,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIncomeRequest) Reset() {
	*x = AddIncomeRequest{}
	mi := &file_Protobuf_club_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIncomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIncomeRequest) ProtoMessage() {}

func (x *AddIncomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIncomeRequest.ProtoReflect.Descriptor instead.
func (*AddIncomeRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{5}
}

func (x *AddIncomeRequest) GetIdClub() int64 {
	if x != nil {
		return x.IdClub
	}
	return 0
}

func (x *AddIncomeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SpendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClub        int64                  `protobuf:"varint,1,opt,name=id_club,json=idClub,proto3" json:"id_club,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendRequest) Reset() {
	*x = SpendRequest{}
	mi := &file_Protobuf_club_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendRequest) ProtoMessage() {}

func (x *SpendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendRequest.ProtoReflect.Descriptor instead.
func (*SpendRequest) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{6}
}

func (x *SpendRequest) GetIdClub() int64 {
	if x != nil {
		return x.IdClub
	}
	return 0
}

func (x *SpendRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ClubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Club          *Club                  `protobuf:"bytes,1,opt,name=club,proto3" json:"club,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClubResponse) Reset() {
	*x = ClubResponse{}
	mi := &file_Protobuf_club_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClubResponse) ProtoMessage() {}

func (x *ClubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClubResponse.ProtoReflect.Descriptor instead.
func (*ClubResponse) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{7}
}

func (x *ClubResponse) GetClub() *Club {
	if x != nil {
		return x.Club
	}
	return nil
}

type ListClubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clubs         []*Club                `protobuf:"bytes,1,rep,name=clubs,proto3" json:"clubs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClubResponse) Reset() {
	*x = ListClubResponse{}
	mi := &file_Protobuf_club_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClubResponse) ProtoMessage() {}

func (x *ListClubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClubResponse.ProtoReflect.Descriptor instead.
func (*ListClubResponse) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{8}
}

func (x *ListClubResponse) GetClubs() []*Club {
	if x != nil {
		return x.Clubs
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Protobuf_club_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Protobuf_club_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Protobuf_club_proto_rawDescGZIP(), []int{9}
}

var File_Protobuf_club_proto protoreflect.FileDescriptor

const file_Protobuf_club_proto_rawDesc = "" +
	"\n" +
	"\x13Protobuf/club.proto\x12\x04club\"q\n" +
	"\x04Club\x12\x17\n" +
	"\aid_club\x18\x01 \x01(\x03R\x06idClub\x12\x1b\n" +
	"\tname_club\x18\x02 \x01(\tR\bnameClub\x12\x1b\n" +
	"\tcity_club\x18\x03 \x01(\tR\bcityClub\x12\x16\n" +
	"\x06budget\x18\x04 \x01(\x03R\x06budget\"e\n" +
	"\x11CreateClubRequest\x12\x1b\n" +
	"\tname_club\x18\x01 \x01(\tR\bnameClub\x12\x1b\n" +
	"\tcity_club\x18\x02 \x01(\tR\bcityClub\x12\x16\n" +
	"\x06budget\x18\x03 \x01(\x03R\x06budget\"-\n" +
	"\x12GetClubByIDRequest\x12\x17\n" +
	"\aid_club\x18\x01 \x01(\x03R\x06idClub\"f\n" +
	"\x11UpdateClubRequest\x12\x17\n" +
	"\aid_club\x18\x01 \x01(\x03R\x06idClub\x12\x1b\n" +
	"\tname_club\x18\x02 \x01(\tR\bnameClub\x12\x1b\n" +
	"\tcity_club\x18\x03 \x01(\tR\bcityClub\",\n" +
	"\x11DeleteClubRequest\x12\x17\n" +
	"\aid_club\x18\x01 \x01(\x03R\x06idClub\"C\n" +
	"\x10AddIncomeRequest\x12\x17\n" +
	"\aid_club\x18\x01 \x01(\x03R\x06idClub\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"?\n" +
	"\fSpendRequest\x12\x17\n" +
	"\aid_club\x18\x01 \x01(\x03R\x06idClub\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\".\n" +
	"\fClubResponse\x12\x1e\n" +
	"\x04club\x18\x01 \x01(\v2\n" +
	".club.ClubR\x04club\"4\n" +
	"\x10ListClubResponse\x12 \n" +
	"\x05clubs\x18\x01 \x03(\v2\n" +
	".club.ClubR\x05clubs\"\a\n" +
	"\x05Empty2\x92\x03\n" +
	"\vClubService\x129\n" +
	"\n" +
	"CreateClub\x12\x17.club.CreateClubRequest\x1a\x12.club.ClubResponse\x12;\n" +
	"\vGetClubByID\x12\x18.club.GetClubByIDRequest\x1a\x12.club.ClubResponse\x122\n" +
	"\vGetAllClubs\x12\v.club.Empty\x1a\x16.club.ListClubResponse\x129\n" +
	"\n" +
	"UpdateClub\x12\x17.club.UpdateClubRequest\x1a\x12.club.ClubResponse\x122\n" +
	"\n" +
	"DeleteClub\x12\x17.club.DeleteClubRequest\x1a\v.club.Empty\x127\n" +
	"\tAddIncome\x12\x16.club.AddIncomeRequest\x1a\x12.club.ClubResponse\x12/\n" +
	"\x05Spend\x12\x12.club.SpendRequest\x1a\x12.club.ClubResponseB\x18Z\x16Club/proto/club;clubpbb\x06proto3"

var (
	file_Protobuf_club_proto_rawDescOnce sync.Once
	file_Protobuf_club_proto_rawDescData []byte
)

func file_Protobuf_club_proto_rawDescGZIP() []byte {
	file_Protobuf_club_proto_rawDescOnce.Do(func() {
		file_Protobuf_club_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Protobuf_club_proto_rawDesc), len(file_Protobuf_club_proto_rawDesc)))
	})
	return file_Protobuf_club_proto_rawDescData
}

var file_Protobuf_club_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Protobuf_club_proto_goTypes = []any{
	(*Club)(nil),               // 0: club.Club
	(*CreateClubRequest)(nil),  // 1: club.CreateClubRequest
	(*GetClubByIDRequest)(nil), // 2: club.GetClubByIDRequest
	(*UpdateClubRequest)(nil),  // 3: club.UpdateClubRequest
	(*DeleteClubRequest)(nil),  // 4: club.DeleteClubRequest
	(*AddIncomeRequest)(nil),   // 5: club.AddIncomeRequest
	(*SpendRequest)(nil),       // 6: club.SpendRequest
	(*ClubResponse)(nil),       // 7: club.ClubResponse
	(*ListClubResponse)(nil),   // 8: club.ListClubResponse
	(*Empty)(nil),              // 9: club.Empty
}
var file_Protobuf_club_proto_depIdxs = []int32{
	0, // 0: club.ClubResponse.club:type_name -> club.Club
	0, // 1: club.ListClubResponse.clubs:type_name -> club.Club
	1, // 2: club.ClubService.CreateClub:input_type -> club.CreateClubRequest
	2, // 3: club.ClubService.GetClubByID:input_type -> club.GetClubByIDRequest
	9, // 4: club.ClubService.GetAllClubs:input_type -> club.Empty
	3, // 5: club.ClubService.UpdateClub:input_type -> club.UpdateClubRequest
	4, // 6: club.ClubService.DeleteClub:input_type -> club.DeleteClubRequest
	5, // 7: club.ClubService.AddIncome:input_type -> club.AddIncomeRequest
	6, // 8: club.ClubService.Spend:input_type -> club.SpendRequest
	7, // 9: club.ClubService.CreateClub:output_type -> club.ClubResponse
	7, // 10: club.ClubService.GetClubByID:output_type -> club.ClubResponse
	8, // 11: club.ClubService.GetAllClubs:output_type -> club.ListClubResponse
	7, // 12: club.ClubService.UpdateClub:output_type -> club.ClubResponse
	9, // 13: club.ClubService.DeleteClub:output_type -> club.Empty
	7, // 14: club.ClubService.AddIncome:output_type -> club.ClubResponse
	7, // 15: club.ClubService.Spend:output_type -> club.ClubResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Protobuf_club_proto_init() }
func file_Protobuf_club_proto_init() {
	if File_Protobuf_club_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Protobuf_club_proto_rawDesc), len(file_Protobuf_club_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Protobuf_club_proto_goTypes,
		DependencyIndexes: file_Protobuf_club_proto_depIdxs,
		MessageInfos:      file_Protobuf_club_proto_msgTypes,
	}.Build()
	File_Protobuf_club_proto = out.File
	file_Protobuf_club_proto_goTypes = nil
	file_Protobuf_club_proto_depIdxs = nil
}
